# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c53c32c66617da0bf697f7e2d8bb8773a866cba500095d821238f98a2564357c13ba80cfede9b2b3dcb0eb97044c3c66953952302989f86d3eeac78e66622f8c

test:
  secret_key_base: 699c5cb68fbc6af317f9e603305e0d7226e0559fc14e88196bfe8b57b662a3d7f5d3e44b1cbdceacef06a61c6504f10f911e592cd8afb28d9c1228a6bf92e68b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
